#!/usr/bin/env groovy

node ('master') {
    git url: 'https://github.com/jfrogtraining/swampup.git'
    def rtServer = Artifactory.newServer url: "http://jfrog.local/artifactory", credentialsId: CREDENTIALS
    def buildInfo = Artifactory.newBuildInfo()
    def tagDockerApp
    def rtDocker
    buildInfo.env.capture = true

    stage('build & deploy') {
       dir ('bintray') {
          sh 'ls'
          sh 'prep.sh'
          tagDockerApp = "jfrog.local:5001/swampup-bintray:${env.BUILD_NUMBER}"
          docker.build(tagDockerApp)
          withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: CREDENTIALS, usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
                rtDocker = Artifactory.docker("${env.USERNAME}", "${env.PASSWORD}")
                rtDocker.push(tagDockerApp, 'docker-stage-local', buildInfo)
                rtServer.publishBuildInfo buildInfo
          }
	  
          def uploadSpec = """{
       	        "files": [
    	        {
		    "pattern": "swampup*.*",
      		    "target":  "generic-local/swampup/swampup-bintray/swampup-bintray-${env.BUILD_NUMBER}-amd64.tgz"
   	        }
 	        ]
          }"""
          rtServer.upload(uploadSpec, buildInfo)
	  }
    }
	   
}
