#!/usr/bin/env groovy

node ('master') {
    git url: 'https://github.com/jfrogtraining/swampup'
    def rtServer = Artifactory.server SERVER_ID
    def rtDocker = Artifactory.docker username: 'jenkins-perf', password: 'jfrog'
    def buildInfo = Artifactory.newBuildInfo()
    buildInfo.env.capture = true
    buildInfo.env.collect()

    stage('Dependencies') {
        dir('automation/docker-framework') {
            try {
                println "Gather Java and Tomcat"

                def downloadFrameworkSpec = readFile "${env.WORKSPACE}/automation/docker-framework/framework-download.json"
                buildInfo = rtServer.download spec: downloadFrameworkSpec
                if (fileExists('jdk/jdk-8-linux-x64.tar.gz') && fileExists('tomcat/apache-tomcat-8.tar.gz')) {
                    println "Downloaded dependencies"
                } else {
                    println "Missing Dependencies either jdk or tomcat - see listing below:"
                    sh 'ls -d */*'
                    throw new FileNotFoundException("Missing Dependencies")
                }
            } catch (Exception e) {
                println "Caught exception during resolution.  Message ${e.message}"
                throw e
            }
        }
    }
    stage('build') {
        dir ('automation/docker-framework') {
            def tagName = "${ARTDOCKER_REGISTRY}/docker-framework:${env.BUILD_NUMBER}"
            docker.build(tagName)
            rtDocker.push(tagName, REPO, buildInfo)
            rtServer.publishBuildInfo(buildInfo)
        }
    }

    stage('test') {
        dir('automation/docker-framework/framework-test') {
            def gradleWarDownload = readFile "${env.WORKSPACE}/automation/docker-framework/gradeWar-download.json"
            rtServer.download(gradleWarDownload)
            def tagDockerFramework "${ARTDOCKER_REGISTRY}/docker-framework-test:${env.BUILD_NUMBER}"
            docker.build(tagDockerFramework)
        }
    }
}
