#!/usr/bin/env groovy

node ('swampup') {
    def rtServer = Artifactory.server SERVER_ID
    def rtDocker = Artifactory.docker username: 'jenkins-perf', password: 'jfrog'
    def buildInfo = Artifactory.newBuildInfo()
    buildInfo.env.capture = true

    stage ('Dependencies') {
        dir ('docker-framework') {
            try {
                println "Gather Java and Tomcat"

                def downloadFrameworkSpec = readFile "${env.WORKSPACE}/framework-download.json"
                buildInfo = rtServer.download spec: downloadFrameworkSpec
                if (fileExists('jdk/jdk-8-linux-x64.tar.gz') && fileExists('tomcat/apache-tomcat-8.tar.gz')) {
                    println "Downloaded dependenices"
                } else {
                    println "Missing Dependencies either jdk or tomcat - see listing below:"
                    sh 'ls -d */*'
                    throw new FileNotFoundException ("Missing Dependencies")
                }
            } catch (Exception e) {
                println "Caught exception during resolution.  Message ${e.message}"
                throw e
            }
        }
    }
    stage ('build') {
        buildInfo.env.collect()
        def tagName = "${ARTDOCKER_REGISTRY}/docker-framework:${env.BUILD_NUMBER}"
        docker.build(tagName)
        rtDocker.push(tagName, REPO, buildInfo)
        #rtServer.publishBuildInfo(buildInfo)
    }

    stage ('test') {
        dir ('docker-framework/framework-test') {
            
        }
    }
